# GitHub Action, die aus den LiaScript-Materialien des Wintersemester 2020/21 ein
# Skript generiert

name: GeneratePdf

on:
  push:
    branches:
      - master

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04
    container:
      image: docker://mirisbowring/texlive_ctan_full:2019
    steps:
      - name: Check out current repository
        uses: actions/checkout@v2
        with:
          ref: master
        # Ausführen des Parsers, der bestimmte Elemente im LiaCode entfernt
      - name: Run preprocessing
        run : |
          mkdir output
          python3 .github/workflows/preprocessing.py
        # Installation der notwendigen Pandoc tools
      - name: Install pandoc
        run: |
          sudo apt install pandoc
      # Generierungsprozess
      - name: Run pandoc markdown to pdf
        run: |
          pandoc --toc -N --top-level-division=chapter -H .github/workflows/head.tex -V linkcolor:blue --pdf-engine=xelatex --listings --include-in-header=.github/workflows/listings.tex -o output/script.pdf *.mdx
      # Speichern als Artifact
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
          
      # Move script to folder
      - name: Copy resulting pdf to separate repository folder
        run: |
             mv ./output/script.pdf ./script/script.pdf
             
      # Commit script file
      - name: Commit pdf
        run: |
             git config --local user.email "action@github.com"
             git config --local user.name "GitHub Action"
             git add ./script/script.pdf
             git commit -m "Add new pdf version of script" || echo "No changes to commit"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
             github_token: ${{ secrets.GITHUB_TOKEN }}
             branch: master
